//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KidsGEPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Member = new HashSet<Member>();
        }
    
        public string SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string city { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Url { get; set; }
        public string UpdateID { get; set; }
        public Nullable<System.DateTime> Updatedt { get; set; }
        public string DisableID { get; set; }
        public Nullable<System.DateTime> Disabledt { get; set; }
        public string Disable { get; set; }
    
        public virtual ICollection<Member> Member { get; set; }
    }
}
