//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontViewRes {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShoppingList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShoppingList() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KidsGEPT.App_LocalResources.Shopping.ShoppingList", typeof(ShoppingList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Quantity 的當地語系化字串。
        /// </summary>
        public static string ShoppingListAmount {
            get {
                return ResourceManager.GetString("ShoppingListAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete the item? 的當地語系化字串。
        /// </summary>
        public static string ShoppingListAreYouSure {
            get {
                return ResourceManager.GetString("ShoppingListAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string ShoppingListButtonCancel {
            get {
                return ResourceManager.GetString("ShoppingListButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm order 的當地語系化字串。
        /// </summary>
        public static string ShoppingListButtonConfirm {
            get {
                return ResourceManager.GetString("ShoppingListButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Print 的當地語系化字串。
        /// </summary>
        public static string ShoppingListButtonPrint {
            get {
                return ResourceManager.GetString("ShoppingListButtonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        public static string ShoppingListButtonYes {
            get {
                return ResourceManager.GetString("ShoppingListButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stock 的當地語系化字串。
        /// </summary>
        public static string ShoppingListClabs {
            get {
                return ResourceManager.GetString("ShoppingListClabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete 的當地語系化字串。
        /// </summary>
        public static string ShoppingListDelete {
            get {
                return ResourceManager.GetString("ShoppingListDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EDT 的當地語系化字串。
        /// </summary>
        public static string ShoppingListDeliverdate {
            get {
                return ResourceManager.GetString("ShoppingListDeliverdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Part No. 的當地語系化字串。
        /// </summary>
        public static string ShoppingListMatnr {
            get {
                return ResourceManager.GetString("ShoppingListMatnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 My shopping cart 的當地語系化字串。
        /// </summary>
        public static string ShoppingListNav {
            get {
                return ResourceManager.GetString("ShoppingListNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string ShoppingListPrice {
            get {
                return ResourceManager.GetString("ShoppingListPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shortage of stock, please comfirm again! 的當地語系化字串。
        /// </summary>
        public static string ShoppingListStockError {
            get {
                return ResourceManager.GetString("ShoppingListStockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subtotal 的當地語系化字串。
        /// </summary>
        public static string ShoppingListSubtotal {
            get {
                return ResourceManager.GetString("ShoppingListSubtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Success 的當地語系化字串。
        /// </summary>
        public static string ShoppingListSuccess {
            get {
                return ResourceManager.GetString("ShoppingListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Confirm 的當地語系化字串。
        /// </summary>
        public static string ShoppingListWarnConfirm {
            get {
                return ResourceManager.GetString("ShoppingListWarnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Material 的當地語系化字串。
        /// </summary>
        public static string ShoppingListZbemattype {
            get {
                return ResourceManager.GetString("ShoppingListZbemattype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        public static string ShoppingListZspec {
            get {
                return ResourceManager.GetString("ShoppingListZspec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Measurement 的當地語系化字串。
        /// </summary>
        public static string ShoppingListZspecu {
            get {
                return ResourceManager.GetString("ShoppingListZspecu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        public static string ShoppingListZtype {
            get {
                return ResourceManager.GetString("ShoppingListZtype", resourceCulture);
            }
        }
    }
}
