//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Leftmenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Leftmenu() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KidsGEPT.Areas.backend.App_LocalResources.Shared.Leftmenu", typeof(Leftmenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 母/子公司維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenubranch {
            get {
                return ResourceManager.GetString("Leftmenubranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統設定 的當地語系化字串。
        /// </summary>
        public static string Leftmenucog {
            get {
                return ResourceManager.GetString("Leftmenucog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 經銷商維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenudealer {
            get {
                return ResourceManager.GetString("Leftmenudealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 交期維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenudelivery {
            get {
                return ResourceManager.GetString("Leftmenudelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語系維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenulanguage {
            get {
                return ResourceManager.GetString("Leftmenulanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 材質維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenumaterial {
            get {
                return ResourceManager.GetString("Leftmenumaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenuorder {
            get {
                return ResourceManager.GetString("Leftmenuorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 夥伴維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenupartner {
            get {
                return ResourceManager.GetString("Leftmenupartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品線維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenuproductline {
            get {
                return ResourceManager.GetString("Leftmenuproductline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 型式維護 的當地語系化字串。
        /// </summary>
        public static string Leftmenuproducttype {
            get {
                return ResourceManager.GetString("Leftmenuproducttype", resourceCulture);
            }
        }
    }
}
