//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontViewRes {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _BondedSealFilter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _BondedSealFilter() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KidsGEPT.App_LocalResources.Shared._BondedSealFilter", typeof(_BondedSealFilter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Width from 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZHEIGHT_BE {
            get {
                return ResourceManager.GetString("_BondedSealFilterZHEIGHT_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Width to 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZHEIGHT_EN {
            get {
                return ResourceManager.GetString("_BondedSealFilterZHEIGHT_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shaft from 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZID_H_BE {
            get {
                return ResourceManager.GetString("_BondedSealFilterZID_H_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shaft to 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZID_H_EN {
            get {
                return ResourceManager.GetString("_BondedSealFilterZID_H_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bore from 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZOD_H_BE {
            get {
                return ResourceManager.GetString("_BondedSealFilterZOD_H_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bore to 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZOD_H_EN {
            get {
                return ResourceManager.GetString("_BondedSealFilterZOD_H_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inch 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZspecuInch {
            get {
                return ResourceManager.GetString("_BondedSealFilterZspecuInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MM 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZspecuMM {
            get {
                return ResourceManager.GetString("_BondedSealFilterZspecuMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the type 的當地語系化字串。
        /// </summary>
        public static string _BondedSealFilterZtypePlaceholder {
            get {
                return ResourceManager.GetString("_BondedSealFilterZtypePlaceholder", resourceCulture);
            }
        }
    }
}
