//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontViewRes {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _SubsituteResult {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _SubsituteResult() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KidsGEPT.App_LocalResources.Shared._SubsituteResult", typeof(_SubsituteResult).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add to cart 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultAddtoCart {
            get {
                return ResourceManager.GetString("_SubsituteResultAddtoCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Quantity 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultAMOUNT {
            get {
                return ResourceManager.GetString("_SubsituteResultAMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the quantity! 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultAmountError {
            get {
                return ResourceManager.GetString("_SubsituteResultAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shopping 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultCart {
            get {
                return ResourceManager.GetString("_SubsituteResultCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stock 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultCLABS {
            get {
                return ResourceManager.GetString("_SubsituteResultCLABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Shortage of stock, unable to add to cart! 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultClabsError {
            get {
                return ResourceManager.GetString("_SubsituteResultClabsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 EDT 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultDELIVERDATE {
            get {
                return ResourceManager.GetString("_SubsituteResultDELIVERDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Part No. 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultMATNR {
            get {
                return ResourceManager.GetString("_SubsituteResultMATNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Repeat! 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultMatnrError {
            get {
                return ResourceManager.GetString("_SubsituteResultMatnrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Price 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultPRICE {
            get {
                return ResourceManager.GetString("_SubsituteResultPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Subtotal 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultSUBTOTAL {
            get {
                return ResourceManager.GetString("_SubsituteResultSUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Material 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultZBEMATTYPE {
            get {
                return ResourceManager.GetString("_SubsituteResultZBEMATTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Size 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultZSPEC {
            get {
                return ResourceManager.GetString("_SubsituteResultZSPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Measurement 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultZSPECU {
            get {
                return ResourceManager.GetString("_SubsituteResultZSPECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Type 的當地語系化字串。
        /// </summary>
        public static string _SubsituteResultZTYPE {
            get {
                return ResourceManager.GetString("_SubsituteResultZTYPE", resourceCulture);
            }
        }
    }
}
