//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontViewRes {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Quick {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quick() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KidsGEPT.App_LocalResources.Stock.Quick", typeof(Quick).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Quantity 的當地語系化字串。
        /// </summary>
        public static string QuickAmount {
            get {
                return ResourceManager.GetString("QuickAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string QuickButtonSearch {
            get {
                return ResourceManager.GetString("QuickButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Loading 的當地語系化字串。
        /// </summary>
        public static string QuickLoading {
            get {
                return ResourceManager.GetString("QuickLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 P/N number 的當地語系化字串。
        /// </summary>
        public static string QuickMatnr {
            get {
                return ResourceManager.GetString("QuickMatnr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inquiry 的當地語系化字串。
        /// </summary>
        public static string QuickNavInquiry {
            get {
                return ResourceManager.GetString("QuickNavInquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Order by part no. 的當地語系化字串。
        /// </summary>
        public static string QuickNavSearch {
            get {
                return ResourceManager.GetString("QuickNavSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 *Please fill in the first 11 digits of material number 的當地語系化字串。
        /// </summary>
        public static string QuickNote {
            get {
                return ResourceManager.GetString("QuickNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please wait! 的當地語系化字串。
        /// </summary>
        public static string QuickPleaseWait {
            get {
                return ResourceManager.GetString("QuickPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search Result 的當地語系化字串。
        /// </summary>
        public static string QuickSearchResult {
            get {
                return ResourceManager.GetString("QuickSearchResult", resourceCulture);
            }
        }
    }
}
